title = "Swedish Pancakes"
date_added = 2018-10-04
author = "dgilman"
type = "breakfast"
cook_time = 30

description = """This is my family's recipe for sweet crepes. We serve them as a meal, eating them one-by-one as they come off the pan."""

ingredients = [
"2 eggs",
"1/3 cup of sugar",
"1 1/4 cup of flour",
"1 1/2 cup of milk",
"scant tsp of salt",
"butter",
"powdered sugar",
]

yield = "14-16 pancakes"

directions = """
Spread a small amount of oil on pan and heat it over medium heat. Mix eggs, sugar, flour, milk and salt in a bowl.

When pan is hot, pour 1/3 of a cup of batter into the pan and spread it thinly over the bottom of the pan by liftin the pan and moving it in a circle. Flip pancake when bubbles start to form on the top side.

To serve, spread butter and powdered sugar on top of pancake and roll tightly. Ground cinnamon, lemon juice and fresh fruit also make excellent fillings.
"""
