sudo: required
dist: xenial
language: python

python:
  - 3.7

install:
  - pip install pipenv
  - pipenv sync

script:
  - pipenv run python cltrecipes.py

deploy:
  provider: pages
  local-dir: output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
